#!/usr/bin/tclsh
# -*- tcl -*-
# Synopsis: fixline1 newpath < input > output
# Author: Don Libes
# Modified by: Sergey Bolshakov <sbolshakov@altlinux.ru>
# Description: change first line of script to load expect as tcl package

# try to match any of the following first lines
#!expect ...
#!../expect ...
#!expectk ...
#!foo/bar/expectk ...
#!/bin/sh ...  (beginning of multiline #! style)
#

set line1 "#!/usr/bin/tclsh"
set with_tk {}

if {[regexp {^#!(?:.*/)*([^ ]+)} [gets stdin] {} interp]} {
    switch -exact -- $interp {
	expectk {
	    set with_tk {package require Tk}
	}
	expect {}
	tclsh { exit 0 }
	sh { exit 0 }
	default {
	    error "FIXME: $interp"
	}
    }
}

puts -nonewline "$line1\npackage require Expect\n$with_tk\n[read stdin]"
